# Use the latest Alpine Linux as the base image
#FROM alpine:latest
FROM ubuntu:jammy

# Set the working directory
WORKDIR /app

# Copy the compiled binary file to the /app directory in the container
COPY dist/app /app/app

# Grant execute permission to the binary file
RUN chmod +x /app/app

# Expose the port the application listens on
# According to your app.py, the Tornado server listens on port 8888 by default
EXPOSE 8888

# Define the command to execute when the container starts
# Run your binary file
ENTRYPOINT ["/app/app"]
