# 使用最新的 Alpine Linux 作为基础镜像
#FROM alpine:latest
FROM ubuntu:jammy

# 设置工作目录
WORKDIR /app

# 将编译好的二进制文件 复制到容器的 /app 目录
COPY dist/app /app/app

# 赋予二进制文件执行权限
RUN chmod +x /app/app

# 暴露应用程序监听的端口
# 根据您的 app.py，Tornado 服务器默认监听 8888 端口
EXPOSE 8888

# 定义容器启动时执行的命令
# 运行您的二进制文件
ENTRYPOINT ["/app/app"]
